[project]
name = "homedashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.3.1",
    "celery[redis]>=5.6.3",
    "django>=6.0.5",
    "gunicorn>=26.0.0",
    "requests>=2.33.1",
    "uvicorn>=0.47.0",
]
