services:
  web_be:
    container_name: web_be
    build:
      context: ../
      dockerfile: ./compose/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    env_file:
      - ../.env
    ports:
      - 8000:8000
