"""
Django settings for homedashboard project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DJANGO_DEBUG"].lower() == "true"

ALLOWED_HOSTS = os.environ["DJANGO_ALLOWED_HOSTS"].split(",")


# Application definition
INSTALLED_APPS = [
    "dashboard.apps.DashboardConfig",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kuala_Lumpur"

USE_I18N = False

USE_TZ = False

REDIS_URL = f"redis://:{os.environ['REDIS_PASSWORD']}@redis:6379/0"

# Django cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Celery Configuration
_API_TASK_FREQUENCY = 2 * 60 * 60  # Every 2 hours

CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_URL = REDIS_URL
CELERY_BEAT_SCHEDULE = {
    "weather_forecast": {
        "task": "services.tasks.get_weather_forecast",
        "schedule": _API_TASK_FREQUENCY,
        "args": (["bangi", "kajang", "nilai"],),
    },
    "train_arrival": {
        "task": "services.tasks.get_train_time",
        "schedule": _API_TASK_FREQUENCY,
        "args": (
            [
                {
                    "route_sname": "Seremban Line",
                    "stations": ["bangi", "kajang"],
                    "direction": "1",
                },
                {
                    "route_sname": "Seremban Line",
                    "stations": ["midvalley"],
                    "direction": "0",
                },
            ],
        ),
    },
    "prayer_time": {
        "task": "services.tasks.get_prayer_time",
        "schedule": _API_TASK_FREQUENCY,
        "args": ("WLY01",),
    },
}
CELERY_IMPORTS = ("services.tasks",)
